volumes:
  temporal:
    driver: local

services:
  temporal:
    image: temporalio/server:1.26.2
    entrypoint: /usr/local/bin/temporal
    command: |
      server start-dev
        --ip 0.0.0.0
        --db-filename /data/temporal.db
    user: "0:0"
    volumes:
      - temporal:/data
    ports:
      - "7233:7233"
      - "8233:8233" # ui
    healthcheck:
      test: [CMD, tctl, cluster, health]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
