name: Test

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.2

      - name: Test
        run: go test -race -count 1 -cover -covermode atomic -coverprofile coverage.txt $(go list ./... | grep -v ./example/)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
